name: Feature Request
description: Suggest new functionality or commands
title: ""
labels: ["feature"]
assignees:
  - geoversed
body:
  - type: textarea
    id: feat-reason
    attributes:
      label: Is your feature request related to a problem?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: ""
    validations:
      required: true
  - type: textarea
    id: feat-impl
    attributes:
      label: Describe the solution you would like
      description: Describe what you want to happen.
      placeholder: Break down each component, describing its purpose.
      value: ""
    validations:
      required: true
  - type: textarea
    id: alt-impl
    attributes:
      label: Describe alternatives you've considered
      description: Optionally, describe alternative solutions you've considered.
      placeholder: Break down each component, describing its purpose.
      value: ""